#!/usr/bin/env python

import requests
import time
from pymongo import MongoClient
import gridfs
import sys
import os
from dotenv import load_dotenv

load_dotenv()

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} [number]")

client = MongoClient(os.getenv("MONGODB_URL"))
db = client["image_db"]
fs = gridfs.GridFS(db)

for id in range(int(sys.argv[1])):
    time.sleep(1)

    response = requests.get("https://cataas.com/cat")
    if response.status_code != 200:
        print("Oops! Something is wrong!")
        break

    file_id = fs.put(
        response.content,
        filename=f"{id}.jpg",
        metadata={"tags": ["cat"], "password": os.getenv("ADMIN_PASSWD")},
    )
    print(f"Image saved in MongoDB with ID: {file_id}")
